Added installation of AD trust and some install improvements.
-- Add ipa-server-adtrust to dependencies
-- Run ipa-adtrust-install on non-replicas if /data/ipa-server-adtrust-install-options is present
-- Allow for a custom, optional, startup script /data/startup.sh
-- Ignore "data" to allow for a data directory in the project to ease
   testing just a little bit.
-- Add Samba lib and config files to volume data list.

diff --git a/ipa-server-configure-first b/ipa-server-configure-first
--- a/ipa-server-configure-first
+++ b/ipa-server-configure-first
@@ -241,6 +241,22 @@ else
 		) | xargs $RUN_CMD -U $IPA_SERVER_INSTALL_OPTS ; then
 		sed -i 's/default_ccache_name/# default_ccache_name/' /data/etc/krb5.conf
 		cp -f /etc/resolv.conf /data/etc/resolv.conf.ipa
+
+		if [ -f /data/ipa-server-adtrust-install-options ]; then
+			ADMIN_PASSWORD=$(cat /data/ipa-server-install-options | grep 'admin-password' | awk -F= '{ print $2 }')
+			echo ${ADMIN_PASSWORD} | kinit admin
+			if ! (
+				cat /data/ipa-server-adtrust-install-options
+				echo "--admin-password=${ADMIN_PASSWORD}"
+				echo --netbios-name="$(hostname -d | awk -F. '{ print $1 }' | tr [:lower:] [:upper:])"
+			) | xargs ipa-adtrust-install -U; then
+				ret=$?
+				echo "FreeIPA server configuration failed: Could not successfully install AD trust."
+				exit $ret
+			fi
+			kdestroy -A
+		fi
+
 		cat /etc/volume-data-mv-list | while read i ; do
 			rm -rf /data$i
 			if [ -e $i ] ; then
@@ -258,11 +274,12 @@ else
 	fi
 fi
 
-if [ -t 0 ] ; then
+if [ -f /data/startup.sh ] ; then
+	/data/startup.sh
+elif [ -t 0 ] ; then
 	echo 'Starting interactive shell.'
 	/bin/bash
 else
 	echo 'Go loop.'
 	while true ; do sleep 1000 & wait $! ; done
 fi
-
